services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.6.0
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: confluentinc/cp-kafka:7.6.0
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: INTERNAL://:9093,EXTERNAL://:9092
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka:9093,EXTERNAL://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  ibm-mq:
    image: icr.io/ibm-messaging/mq:latest
    container_name: ibm-mq
    hostname: ibm-mq
    ports:
      - "1414:1414"   # MQ listener
      - "9443:9443"   # Web console
    environment:
      LICENSE: accept
      MQ_QMGR_NAME: QM1
      MQ_ADMIN_PASSWORD: admin
      MQ_APP_PASSWORD: app
    volumes:
      - mqdata:/mnt/mqm
      
volumes:
  mqdata:


#  xti-bank-api:
#    build:
#      context: .
#      dockerfile: Dockerfile
#    container_name: xti-bank-api
#    depends_on:
#      - kafka
#      - zookeeper
#    ports:
#      - "8080:8080"
#    environment:
#      SPRING_DATA_MONGODB_URI: mongodb://host.docker.internal:27017
#      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
