version: "3.9"
services:
  mongodb:
    image: mongo:7
    container_name: xti-mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: xti-bank

  xti-bank-api:
    build: xti-bank-api/.
    ports:
      - "8080:8080"
    environment:
      SPRING_DATA_MONGODB_URI: mongodb://mongodb:27017/xti-bank
    depends_on:
      - mongodb
